### ISSUE TITLE
Refactor the plugin overhead

### ISSUE THREAD

**Issue by metodiew** [metodiew/trololo#1]
I literally was blown away of the massive overhead of all unused files, classes, functions and things like that, so it was pretty normal to add this issues as #1 of the "project"

**Comment by xavortm** [comment]
Yes yes, a valid point. I think after all the spaghetti code its time to rewrite the whole platform. You have green light!

**Comment by metodiew** [comment]
I'll assign the issue to me and will clean the code a bit. Yesterday was a bit grumpy while creating the issue :P
